name: Release
run-name:  build release by ${{ github.actor }} 🚀
on:
  release:
    types: [created,published]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64, arm, ppc64le, ppc64, s390x]
    steps:
      - run: echo "🎉 由 ${{ github.event_name }} 事件触发"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 所处位置 ${{ github.repository }} "
      - name: Upload
        uses: wangyoucao577/go-release-action@v1.30
        with:
          pre_command: pwd && ls
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: https://dl.google.com/go/go1.21.0.linux-amd64.tar.gz
          project_path: "./go"
      - run: echo "🍏 任务状态 ${{ job.status }}."
